apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-manager.fullname" . }}-secret
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "secrets.databaseUrl is required" .Values.secrets.databaseUrl | quote }}
